### ISSUE TITLE
Documentation: Does not list any requirements for what version of node is required

### ISSUE THREAD

**Issue by misilot** [artefactual/atom#1790]
### Current Behavior

**Steps to reproduce the behavior**
1. Go to https://www.accesstomemory.org/en/docs/2.8/admin-manual/installation/ubuntu/#compile-bootstrap-5-theme-files
2. system might not have node installed, so this fails, or with Ubuntu 20.04 has an older version than needed?

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
```

Which this seems to install correctly, but `npm run build` fails.

```

> atom@0.0.0 build /klib/webdata/atom
> webpack

assets by status 1.17 MiB [cached] 5 assets
runtime modules 1.35 KiB 6 modules
orphan modules 31.1 KiB [orphan] 5 modules
modules by path ./node_modules/ 2.16 MiB 126 modules
modules by path ./plugins/arDominionB5Plugin/ 134 KiB
  modules by path ./plugins/arDominionB5Plugin/js/*.js 103 KiB 28 modules
  ./plugins/arDominionB5Plugin/webpack.entry.js + 4 modules 31.1 KiB [built] [code generated]
  ./plugins/arDominionB5Plugin/scss/main.scss 39 bytes [built] [code generated] [1 error]
modules by path ./js/*.js 55.6 KiB
  ./js/blank.js 629 bytes [built] [code generated]
  ./js/editingHistory.js 2.18 KiB [built] [code generated]
  + 8 modules
modules by path ./vendor/yui/ 265 KiB
  ./vendor/yui/yahoo-dom-event/yahoo-dom-event.js 36 KiB [built] [code generated]
  ./vendor/yui/connection/connection.js 37 KiB [built] [code generated]
  + 2 modules

WARNING in ./plugins/arDominionB5Plugin/scss/main.scss (./plugins/arDominionB5Plugin/scss/main.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[3]!./plugins/arDominionB5Plugin/scss/main.scss)
Module Warning (from ./node_modules/resolve-url-loader/index.js):
resolve-url-loader: webpack misconfiguration
  webpack or the upstream loader did not supply a source-map
 @ ./plugins/arDominionB5Plugin/scss/main.scss
 @ ./plugins/arDominionB5Plugin/webpack.entry.js 2:0-26

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/bootstrap/js/dist/tooltip.js 7:90-115
Module not found: Error: Can't resolve '@popperjs/core' in '/klib/webdata/atom/node_modules/bootstrap/js/dist'
 @ ./plugins/arDominionB5Plugin/js/tooltip.js 1:0-48 5:28-35
 @ ./plugins/arDominionB5Plugin/js/main.js 15:0-19
 @ ./plugins/arDominionB5Plugin/webpack.entry.js 1:0-19

ERROR in ./plugins/arDominionB5Plugin/scss/main.scss (./plugins/arDominionB5Plugin/scss/main.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[3]!./plugins/arDominionB5Plugin/scss/main.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
globalThis is not defined
 @ ./plugins/arDominionB5Plugin/scss/main.scss
 @ ./plugins/arDominionB5Plugin/webpack.entry.js 2:0-26

ERROR in ./plugins/arDominionB5Plugin/scss/main.scss (./plugins/arDominionB5Plugin/scss/main.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[3]!./plugins/arDominionB5Plugin/scss/main.scss)
Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  PostCSS received undefined instead of CSS string
  at new Input (/klib/webdata/atom/node_modules/postcss/lib/input.js:24:13)
    at encodeError (/klib/webdata/atom/node_modules/resolve-url-loader/index.js:274:12)
    at onFailure (/klib/webdata/atom/node_modules/resolve-url-loader/index.js:215:14)
 @ ./plugins/arDominionB5Plugin/scss/main.scss
 @ ./plugins/arDominionB5Plugin/webpack.entry.js 2:0-26

ERROR in ./plugins/arDominionB5Plugin/scss/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  PostCSS received undefined instead of CSS string
  at new Input (/klib/webdata/atom/node_modules/postcss/lib/input.js:24:13)
    at encodeError (/klib/webdata/atom/node_modules/resolve-url-loader/index.js:274:12)
    at onFailure (/klib/webdata/atom/node_modules/resolve-url-loader/index.js:215:14)
    at tryRunOrWebpackError (/klib/webdata/atom/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/klib/webdata/atom/node_modules/webpack/lib/Compilation.js:5241:12)
    at __webpack_require__ (/klib/webdata/atom/node_modules/webpack/lib/Compilation.js:5198:18)
    at asyncLib.eachLimit.err (/klib/webdata/atom/node_modules/webpack/lib/Compilation.js:5270:20)
    at symbolIterator (/klib/webdata/atom/node_modules/neo-async/async.js:3485:9)
    at done (/klib/webdata/atom/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/klib/webdata/atom/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/klib/webdata/atom/node_modules/tapable/lib/Hook.js:18:14)
    at asyncLib.eachLimit (/klib/webdata/atom/node_modules/webpack/lib/Compilation.js:5176:43)
    at symbolIterator (/klib/webdata/atom/node_modules/neo-async/async.js:3482:9)
-- inner error --
Error: Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  PostCSS received undefined instead of CSS string
  at new Input (/klib/webdata/atom/node_modules/postcss/lib/input.js:24:13)
    at encodeError (/klib/webdata/atom/node_modules/resolve-url-loader/index.js:274:12)
    at onFailure (/klib/webdata/atom/node_modules/resolve-url-loader/index.js:215:14)
    at Object.<anonymous> (/klib/webdata/atom/node_modules/css-loader/dist/cjs.js!/klib/webdata/atom/node_modules/resolve-url-loader/index.js!/klib/webdata/atom/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[3]!/klib/webdata/atom/plugins/arDominionB5Plugin/scss/main.scss:1:7)
    at compilation.hooks.executeModule.tap (/klib/webdata/atom/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:452:10)
    at Hook.eval [as call] (eval at create (/klib/webdata/atom/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/klib/webdata/atom/node_modules/tapable/lib/Hook.js:14:14)
    at tryRunOrWebpackError (/klib/webdata/atom/node_modules/webpack/lib/Compilation.js:5243:39)
    at tryRunOrWebpackError (/klib/webdata/atom/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/klib/webdata/atom/node_modules/webpack/lib/Compilation.js:5241:12)
    at __webpack_require__ (/klib/webdata/atom/node_modules/webpack/lib/Compilation.js:5198:18)
    at asyncLib.eachLimit.err (/klib/webdata/atom/node_modules/webpack/lib/Compilation.js:5270:20)
    at symbolIterator (/klib/webdata/atom/node_modules/neo-async/async.js:3485:9)

Generated code for /klib/webdata/atom/node_modules/css-loader/dist/cjs.js!/klib/webdata/atom/node_modules/resolve-url-loader/index.js!/klib/webdata/atom/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[3]!/klib/webdata/atom/plugins/arDominionB5Plugin/scss/main.scss
1 | throw new Error("Module build failed (from ./node_modules/resolve-url-loader/index.js):\nError: resolve-url-loader: error processing CSS\n  PostCSS received undefined instead of CSS string\n  at new Input (/klib/webdata/atom/node_modules/postcss/lib/input.js:24:13)\n    at encodeError (/klib/webdata/atom/node_modules/resolve-url-loader/index.js:274:12)\n    at onFailure (/klib/webdata/atom/node_modules/resolve-url-loader/index.js:215:14)");
 @ ./plugins/arDominionB5Plugin/webpack.entry.js 2:0-26

2 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.91.0 compiled with 4 errors and 1 warning in 43483 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atom@0.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

### Expected Behavior

Installs modules, and and builds the new theme?

### Version used

AtoM v2.8.0

### Operating System and version

Ubuntu 20.04

### Default installation culture

en

### PHP version

PHP 7.4

**Comment by anvit** [comment]
@misilot Thanks for reporting this! I've just created a docs issue in the atom-docs repo for this: https://github.com/artefactual/atom-docs/issues/279

Node v18+ should be able to resolve this error for you. I'm curious which version of node you have running though.

**Comment by misilot** [comment]
@anvit v10.19.0 is what we have for v2.6.4.

I believe that was the recommended version there? or at least got installed through the ansible playbook we had used from Artefactual at the time.

**Comment by anvit** [comment]
@misilot ah okay thanks for letting me know! The node version number has been bumped since we added (and more recently updated) Bootstrap 5.
